name: Code checks

on:
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install dependencies
        run: |
          pip install flake8  # Install flake8 linter
          pip install pytest coverage bandit safety sphinx mypy  # Install additional tools

      - name: Run linter
        run: flake8

      - name: Run unit tests
      # Running unit tests ensures that individual components of code work as expected.
        run: pytest

      - name: Run code coverage
      # Checking code coverage to ensure tests cover a sufficient portion of codebase.
        run: coverage run -m pytest
        
        # Collect coverage report
      - name: Coverage report
        run: coverage report

      - name: Run security scan
      # Performing security scans helps identify vulnerabilities and potential security issues in code.
        run: bandit -r .

      - name: Check for dependency vulnerabilities
      # ensures that our project's dependencies are free from known security vulnerabilities. 
        run: safety check

      #- name: Build documentation
      # Verifying documentation consistency and correctness can help maintain a clear and up-to-date project documentation.
      #  run: sphinx-build -b html docs sourcedir

      - name: Type check
      # ensures that code follows the specified type hints, helping catch potential type-related errors.
        run: mypy 
