name: Code checks

on:
  pull_request:
    branches:
      - main  # will change the name if we want to create this on "master"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: pip install flake8  # Install flake8 linter

      - name: Run linter
        run: flake8
